services:
  celery_render:
    container_name: celery_render
    restart: always
    build:
      context: .
    command: celery -A celeryworker worker -l INFO --hostname=Sever-Content --concurrency=2 -Q render_video_content
    volumes:
      - .:/app
  celery_render_reup:
    container_name: celery_render_reup
    restart: always
    build:
      context: .
    command: celery -A celeryworker worker -l INFO --hostname=Sever-Reup --concurrency=1 -Q render_video_reupload
    volumes:
      - .:/app
