version: '3.8'
services:
  celery_render_reup:
    container_name: celery
    restart: always
    build:
      context: .
    command: python start_celery_reup.py
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge


      
