version: '3.8'
services:
  video_screen:
    build:
      context: .
    container_name: video_screen
    volumes:
      - .:/app
    command: sh /app/download.sh
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "test", "-f", "/app/video_screen/ready.txt"]
      interval: 1m30s
      timeout: 20s
      retries: 5

  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: python start_celery_reup.py
    volumes:
      - .:/app
    networks:
      - app_network
    environment:
      - TZ=Asia/Ho_Chi_Minh

networks:
  app_network:
    driver: bridge


      
