version: '3.8'
services:
  celery_render:
    container_name: celery_render
    restart: always
    build:
      context: .
    command: python start_celery_content.py
    volumes:
      - .:/app
    networks:
      - app_network
  voicevox_render:
    container_name: voicevox_render
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "127.0.0.1:50025:50021"
    restart: always 
    volumes:
      - .:/app
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
      
