services:
  celery_render:
    container_name: celery_render
    restart: always
    build:
      context: .
    command: python Start_celery_app.py
    volumes:
      - .:/app
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Sử dụng tất cả GPU có sẵn, hoặc có thể chỉ định số lượng cụ thể như 1,2,...
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Hoặc chỉ định GPU cụ thể như "0" hoặc "0,1"
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video  # Bao gồm khả năng mã hóa video
    
  voicevox_render:
    container_name: voicevox_render
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "127.0.0.1:50025:50025"
    restart: always
    volumes:
      - .:/app

