services:
  celery_render_reup:
    container_name: celery_render_reup
    restart: always
    build:
      context: .
    command: python start_celery_reup.py
    volumes:
      - .:/app
    network_mode: "host"
      
