# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.youtube.com    TRUE    /       TRUE    7766329239      __Secure-3PSID  g.a000qQjOacoCNZTsLm7u0gTILAHtbu2pm5rTPOYDwqm8txsIoRKTpQJIomL6VVQ9KFES0KYQogACgYKAXYSARESFQHGX2MimLnCT88>
.youtube.com    TRUE    /       TRUE    1731770773      GPS     1
.youtube.com    TRUE    /       TRUE    1763305239      __Secure-1PSIDTS        sidts-CjIBQT4rX_QJ1vks1u9QKDbfi58bSfbjh-aqzovy3_FGqYvWCL5YjazyrbMz1YXYKMTBoBAA
.youtube.com    TRUE    /       TRUE    1766329239      __Secure-3PAPISID       TEhafGfW16iJwsLI/AZIWLQrlfq7uBauyH
.youtube.com    TRUE    /       TRUE    7763306303      __Secure-3PSIDCC        AKEyXzVXqAXF8wzUNMidwdbed6iBWm9kZjJTs-ZVBul7RMwJeP5bvgmlsx02b1J1kzF9cWl6LA
.youtube.com    TRUE    /       TRUE    7763305239      __Secure-3PSIDTS        sidts-CjIBQT4rX_QJ1vks1u9QKDbfi58bSfbjh-aqzovy3_FGqYvWCL5YjazyrbMz1YXYKMTBoBAA
.youtube.com    TRUE    /       FALSE   0       PREF    tz=UTC&f4=4000000&f5=30000&hl=en
.youtube.com    TRUE    /       TRUE    1765897734      __Secure-YEC    CgtiNHJhb0tqS1M1RSjl8uK5BjIKCgJERRIEEgAgEA%3D%3D
.youtube.com    TRUE    /       TRUE    1765898725      VISITOR_PRIVACY_METADATA        CgJERRIEEgAgEA%3D%3D
.youtube.com    TRUE    /       TRUE    1747321735      __Secure-ROLLOUT_TOKEN  COOOv9a8wZvOSBCQqr__kOGJAxiQqr__kOGJAw%3D%3D
.youtube.com    TRUE    /       TRUE    1731774326      SAPISID TEhafGfW16iJwsLI/AZIWLQrlfq7uBauyH