# Generated by Django 5.0.6 on 2024-06-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Font_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=100)),
                ('channel_intro_active', models.BooleanField(blank=True, default=False)),
                ('channel_intro_url', models.TextField(blank=True, default='')),
                ('channel_outro_active', models.BooleanField(blank=True, default=False)),
                ('channel_outro_url', models.TextField(blank=True, default='')),
                ('channel_logo_active', models.BooleanField(blank=True, default=False)),
                ('channel_logo_url', models.TextField(blank=True, default='')),
                ('channel_logo_position', models.TextField(blank=True, default='left', max_length=100)),
                ('channel_font_size', models.IntegerField(blank=True, default=30)),
                ('channel_font_bold', models.BooleanField(blank=True, default=False)),
                ('channel_font_italic', models.BooleanField(blank=True, default=False)),
                ('channel_font_underline', models.BooleanField(blank=True, default=False)),
                ('channel_font_strikeout', models.BooleanField(blank=True, default=False)),
                ('channel_font_color', models.TextField(blank=True, default='#000000', max_length=100)),
                ('channel_font_color_opacity', models.IntegerField(blank=True, default=100)),
                ('channel_font_color_troke', models.TextField(blank=True, default='#000000', max_length=100)),
                ('channel_font_color_troke_opacity', models.IntegerField(blank=True, default=100)),
                ('channel_stroke_text', models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=10)),
                ('channel_font_background', models.TextField(blank=True, default='#ffffff', max_length=100)),
                ('channel_font_background_opacity', models.IntegerField(blank=True, default=0)),
                ('channel_font_subtitle', models.TextField(default='Đây là phần subtittel của kênh')),
                ('channel_voice', models.IntegerField(blank=True, default=1)),
                ('channel_voice_style', models.IntegerField(blank=True, default=0)),
                ('channel_voice_speed', models.IntegerField(blank=True, default=50)),
                ('channel_voice_pitch', models.IntegerField(blank=True, default=50)),
                ('channel_voice_volume', models.IntegerField(blank=True, default=50)),
                ('channel_text_voice', models.TextField(blank=True, default='')),
                ('channel_title', models.TextField(blank=True, default='')),
                ('channel_description', models.TextField(blank=True, default='')),
                ('channel_keywords', models.TextField(blank=True, default='')),
                ('channel_time_upload', models.TextField(blank=True, default='')),
                ('channel_url', models.TextField(blank=True, default='')),
                ('channel_email_login', models.TextField(blank=True, default='')),
                ('channel_vps_upload', models.TextField(blank=True, default='')),
                ('channel_money', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('channel_view_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='syle_voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_style', models.IntegerField(blank=True, default=0)),
                ('name_voice', models.CharField(blank=True, max_length=100)),
                ('style_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voice_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('speaker_uuid', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
