# Generated by Django 5.0.6 on 2024-08-01 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilechannel',
            name='channel_voice_pitch',
        ),
        migrations.RemoveField(
            model_name='profilechannel',
            name='channel_voice_speed',
        ),
        migrations.RemoveField(
            model_name='profilechannel',
            name='channel_voice_volume',
        ),
        migrations.AddField(
            model_name='font_text',
            name='font_language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='syle_voice',
            name='channel_voice_pitch',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='syle_voice',
            name='channel_voice_speed',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='syle_voice',
            name='channel_voice_style',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='syle_voice',
            name='channel_voice_volume',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AlterField(
            model_name='profilechannel',
            name='channel_font_color',
            field=models.TextField(blank=True, default='##FFFFFF', max_length=100),
        ),
        migrations.AlterField(
            model_name='profilechannel',
            name='channel_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.voice_language'),
        ),
        migrations.AlterField(
            model_name='profilechannel',
            name='channel_voice_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.syle_voice'),
        ),
    ]
