# Generated by Django 5.0.6 on 2024-08-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_profilechannel_channel_voice_pitch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilechannel',
            name='channel_voice',
        ),
    ]
