# Generated by Django 5.0.6 on 2024-08-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profilechannel_is_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilechannel',
            name='is_content',
        ),
        migrations.AddField(
            model_name='folder',
            name='is_content',
            field=models.BooleanField(default=True),
        ),
    ]
