# Generated by Django 5.0.6 on 2024-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_profilechannel_is_content_folder_is_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechannel',
            name='channel_font_subtitle',
            field=models.TextField(blank=True, default='Đây là phần subtittel của kênh'),
        ),
    ]
