# Generated by Django 5.0.6 on 2024-06-07 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Key_Azure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_key', models.TextField(blank=True, default='')),
                ('endpoint', models.TextField(blank=True, default='')),
                ('timenow', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTextVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.URLField(max_length=100)),
                ('count_text', models.IntegerField()),
                ('id_channel', models.URLField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('text_video', models.TextField()),
                ('timenow', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.folder')),
            ],
        ),
        migrations.CreateModel(
            name='video_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('timenow', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.folder')),
                ('profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profilechannel')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_video', models.TextField(max_length=100)),
                ('url_video_youtube', models.TextField(max_length=100)),
                ('text_content', models.TextField(blank=True, default='')),
                ('text_content_2', models.TextField(blank=True, default='')),
                ('status_video', models.TextField(blank=True, default='Đang Chờ Cập Nhập Tiêu Đề & Thumnail')),
                ('is_render_start', models.BooleanField(blank=True, default=False)),
                ('video_image', models.TextField(blank=True, default='')),
                ('url_thumbnail', models.TextField(blank=True)),
                ('url_video', models.TextField(blank=True)),
                ('intro_active', models.BooleanField(blank=True, default=False)),
                ('intro_url', models.TextField(blank=True, default='')),
                ('outro_active', models.BooleanField(blank=True, default=False)),
                ('outro_url', models.TextField(blank=True, default='')),
                ('logo_active', models.BooleanField(blank=True, default=False)),
                ('logo_url', models.TextField(blank=True, default='')),
                ('logo_position', models.TextField(blank=True, default='left', max_length=100)),
                ('font_text', models.TextField(blank=True, default='')),
                ('font_size', models.IntegerField(blank=True, default=30)),
                ('font_bold', models.BooleanField(blank=True, default=False)),
                ('font_italic', models.BooleanField(blank=True, default=False)),
                ('font_underline', models.BooleanField(blank=True, default=False)),
                ('font_strikeout', models.BooleanField(blank=True, default=False)),
                ('font_color', models.TextField(blank=True, default='#000000', max_length=100)),
                ('font_color_opacity', models.IntegerField(blank=True, default=0)),
                ('font_color_troke', models.TextField(blank=True, default='#000000', max_length=100)),
                ('font_color_troke_opacity', models.IntegerField(blank=True, default=0)),
                ('stroke_text', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10)),
                ('font_background', models.TextField(blank=True, default='#ffffff', max_length=100)),
                ('channel_font_background_opacity', models.IntegerField(blank=True, default=0)),
                ('voice', models.IntegerField(blank=True, default=1)),
                ('voice_style', models.IntegerField(blank=True, default=0)),
                ('voice_speed', models.IntegerField(blank=True, default=50)),
                ('voice_pitch', models.IntegerField(blank=True, default=50)),
                ('voice_volume', models.IntegerField(blank=True, default=50)),
                ('text_voice', models.TextField(blank=True, default='')),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('time_upload', models.TextField(blank=True, default='')),
                ('date_upload', models.TextField(blank=True, default='')),
                ('timenow', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.folder')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profilechannel')),
            ],
        ),
        migrations.CreateModel(
            name='Count_Use_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_thumnail', models.BooleanField(default=False)),
                ('edit_title', models.BooleanField(default=False)),
                ('creade_video', models.BooleanField(default=False)),
                ('title', models.TextField(blank=True, default='')),
                ('url_thumnail', models.TextField(blank=True, default='')),
                ('timenow', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('videoRender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.videorender')),
            ],
        ),
    ]
