# Generated by Django 5.0.6 on 2024-08-08 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0007_alter_profilechannel_channel_font_subtitle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Voice_ttsmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Api_Voice_ttsmaker', models.TextField(blank=True, default='')),
                ('timenow', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIKeyGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTextVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.URLField(max_length=100)),
                ('count_text', models.IntegerField()),
                ('id_channel', models.URLField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('text_video', models.TextField()),
                ('timenow', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.folder')),
            ],
        ),
        migrations.CreateModel(
            name='video_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('timenow', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.folder')),
                ('profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profilechannel')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_video', models.TextField(blank=True, max_length=100)),
                ('url_video_youtube', models.TextField(blank=True, max_length=100)),
                ('text_content', models.TextField(blank=True, default='')),
                ('text_content_2', models.TextField(blank=True, default='')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status_video', models.TextField(blank=True, default='Đang Chờ Cập Nhập Tiêu Đề & Thumnail')),
                ('is_render_start', models.BooleanField(blank=True, default=False)),
                ('url_audio', models.TextField(blank=True, default='')),
                ('url_subtitle', models.TextField(blank=True, default='')),
                ('video_image', models.TextField(blank=True, default='')),
                ('url_thumbnail', models.TextField(blank=True)),
                ('url_video', models.TextField(blank=True)),
                ('intro_active', models.BooleanField(blank=True, default=False)),
                ('intro_url', models.TextField(blank=True, default='')),
                ('outro_active', models.BooleanField(blank=True, default=False)),
                ('outro_url', models.TextField(blank=True, default='')),
                ('logo_active', models.BooleanField(blank=True, default=False)),
                ('logo_url', models.TextField(blank=True, default='')),
                ('logo_position', models.TextField(blank=True, default='left', max_length=100)),
                ('font_size', models.IntegerField(blank=True, default=30)),
                ('font_bold', models.BooleanField(blank=True, default=False)),
                ('font_italic', models.BooleanField(blank=True, default=False)),
                ('font_underline', models.BooleanField(blank=True, default=False)),
                ('font_strikeout', models.BooleanField(blank=True, default=False)),
                ('font_color', models.TextField(blank=True, default='#FFFFFF', max_length=100)),
                ('font_color_opacity', models.IntegerField(blank=True, default=100)),
                ('font_color_troke', models.TextField(blank=True, default='#000000', max_length=100)),
                ('font_color_troke_opacity', models.IntegerField(blank=True, default=0)),
                ('stroke_text', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10)),
                ('font_background', models.TextField(blank=True, default='#ffffff', max_length=100)),
                ('channel_font_background_opacity', models.IntegerField(blank=True, default=0)),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('time_upload', models.TextField(blank=True, default='')),
                ('date_upload', models.TextField(blank=True, default='')),
                ('timenow', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_voice_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.syle_voice')),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.folder')),
                ('font_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.font_text')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profilechannel')),
            ],
        ),
        migrations.CreateModel(
            name='Count_Use_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_thumnail', models.BooleanField(default=False)),
                ('edit_title', models.BooleanField(default=False)),
                ('creade_video', models.BooleanField(default=False)),
                ('video_render_success', models.BooleanField(default=False)),
                ('video_render_fail', models.BooleanField(default=False)),
                ('video_render_waiting', models.BooleanField(default=False)),
                ('upload_success', models.BooleanField(default=False)),
                ('upload_fail', models.BooleanField(default=False)),
                ('Waiting_upload', models.BooleanField(default=False)),
                ('title', models.TextField(blank=True, default='')),
                ('url_thumnail', models.TextField(blank=True, default='')),
                ('timenow', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('videoRender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.videorender')),
            ],
        ),
    ]
