# Generated by Django 5.0.6 on 2024-06-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorender',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
