# Generated by Django 5.0.6 on 2024-08-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorender',
            name='url_reupload',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
