# Generated by Django 5.0.6 on 2024-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_videorender_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorender',
            name='url_audio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videorender',
            name='url_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='videorender',
            name='font_color',
            field=models.TextField(blank=True, default='#FFFFFF', max_length=100),
        ),
        migrations.AlterField(
            model_name='videorender',
            name='font_color_opacity',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='videorender',
            name='voice_style',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
