# Generated by Django 5.0.6 on 2024-07-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_videorender_url_audio_videorender_url_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorender',
            name='worker_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
