# Generated by Django 5.0.6 on 2024-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0004_videorender_worker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Voice_ttsmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Api_Voice_ttsmaker', models.TextField(blank=True, default='')),
                ('timenow', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
