# Generated by Django 5.0.6 on 2024-07-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0005_api_voice_ttsmaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorender',
            name='name_video',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videorender',
            name='url_video_youtube',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
