# Generated by Django 5.0.6 on 2024-07-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0006_alter_videorender_name_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='count_use_data',
            name='Waiting_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='count_use_data',
            name='upload_fail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='count_use_data',
            name='upload_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='count_use_data',
            name='video_render_fail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='count_use_data',
            name='video_render_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='count_use_data',
            name='video_render_waiting',
            field=models.BooleanField(default=False),
        ),
    ]
