# Generated by Django 5.0.6 on 2024-07-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0007_count_use_data_waiting_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorender',
            name='url_text_video',
            field=models.ManyToManyField(related_name='VideoRender', to='render.datatextvideo'),
        ),
    ]
