# Generated by Django 5.0.6 on 2024-08-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_profilechannel_channel_voice'),
        ('render', '0009_remove_videorender_url_text_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videorender',
            name='text_voice',
        ),
        migrations.RemoveField(
            model_name='videorender',
            name='voice',
        ),
        migrations.RemoveField(
            model_name='videorender',
            name='voice_pitch',
        ),
        migrations.RemoveField(
            model_name='videorender',
            name='voice_speed',
        ),
        migrations.RemoveField(
            model_name='videorender',
            name='voice_style',
        ),
        migrations.RemoveField(
            model_name='videorender',
            name='voice_volume',
        ),
        migrations.AddField(
            model_name='videorender',
            name='channel_voice_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.syle_voice'),
        ),
    ]
