# Generated by Django 5.0.6 on 2024-08-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_profilechannel_channel_font_subtitle'),
        ('render', '0010_remove_videorender_text_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorender',
            name='font_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.font_text'),
        ),
    ]
